services:
  roboHire-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date +%Y%m%d-%H%M)}
    image: harbor.lightark.cc/iagent/robohire-api:${BUILD_DATE:-latest}
    container_name: robohire-api
    environment:
      - WORKERS=1
    env_file:
      - .env
    ports:
      - "33607:80"
      - "34607:4607"
    volumes:
      - ./logs/roboHire-api:/app/logs
      - ./api_data:/data
    restart: unless-stopped
    extra_hosts:
      - "newapi.lightark.ai:13.67.119.46"