import { useState, useEffect, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import axios from '../../lib/axios';

// ─── Types ───────────────────────────────────────────────────

interface TaskJob { id: string; title: string; status: string }
interface TaskResume { id: string; name: string }
interface TaskInterview { id: string; candidateName: string; status: string }
interface TaskUser { id: string; name: string | null; email: string }

interface Task {
  id: string;
  userId: string;
  createdById: string | null;
  type: string;
  category: string;
  assigneeType: string;
  title: string;
  description: string | null;
  actionUrl: string | null;
  actionLabel: string | null;
  jobId: string | null;
  resumeId: string | null;
  interviewId: string | null;
  priority: string;
  dueAt: string | null;
  slaDeadline: string | null;
  escalatedAt: string | null;
  status: string;
  completedAt: string | null;
  completedBy: string | null;
  dismissReason: string | null;
  triggerEvent: string;
  isAutoGenerated: boolean;
  archivedAt: string | null;
  createdAt: string;
  updatedAt: string;
  job: TaskJob | null;
  resume: TaskResume | null;
  interview: TaskInterview | null;
  createdBy: TaskUser | null;
}

interface TaskStats {
  total: number;
  actionRequired: number;
  pending: number;
  inProgress: number;
  completed: number;
  dismissed: number;
  autoCompleted: number;
  overdue: number;
  byPriority: { critical: number; high: number; medium: number; low: number };
  byCategory: { pipeline: number; evaluation: number; sourcing: number; communication: number; admin: number };
}

// ─── Constants ───────────────────────────────────────────────

const PRIORITY_STYLES: Record<string, { color: string; bg: string; dot: string; key: string }> = {
  critical: { color: 'text-red-700', bg: 'bg-red-50 border-red-200', dot: 'bg-red-500', key: 'tasks.priority.critical' },
  high:     { color: 'text-amber-700', bg: 'bg-amber-50 border-amber-200', dot: 'bg-amber-500', key: 'tasks.priority.high' },
  medium:   { color: 'text-blue-700', bg: 'bg-blue-50 border-blue-200', dot: 'bg-blue-500', key: 'tasks.priority.medium' },
  low:      { color: 'text-slate-600', bg: 'bg-slate-50 border-slate-200', dot: 'bg-slate-400', key: 'tasks.priority.low' },
};

const CATEGORY_KEYS: Record<string, string> = {
  pipeline: 'tasks.category.pipeline',
  evaluation: 'tasks.category.evaluation',
  sourcing: 'tasks.category.sourcing',
  communication: 'tasks.category.communication',
  admin: 'tasks.category.admin',
};

const STATUS_STYLES: Record<string, { key: string; color: string }> = {
  pending: { key: 'tasks.status.pending', color: 'text-amber-600 bg-amber-50' },
  in_progress: { key: 'tasks.status.inProgress', color: 'text-blue-600 bg-blue-50' },
  completed: { key: 'tasks.status.completed', color: 'text-emerald-600 bg-emerald-50' },
  dismissed: { key: 'tasks.status.dismissed', color: 'text-slate-500 bg-slate-100' },
  auto_completed: { key: 'tasks.status.autoCompleted', color: 'text-purple-600 bg-purple-50' },
  expired: { key: 'tasks.status.expired', color: 'text-red-500 bg-red-50' },
};

// ─── Helpers ─────────────────────────────────────────────────

function timeAgo(dateStr: string, t: (key: string, fallback: string, opts?: Record<string, unknown>) => string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return t('tasks.time.justNow', 'just now');
  if (mins < 60) return t('tasks.time.minutesAgo', '{{count}}m ago', { count: mins });
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return t('tasks.time.hoursAgo', '{{count}}h ago', { count: hrs });
  const days = Math.floor(hrs / 24);
  return t('tasks.time.daysAgo', '{{count}}d ago', { count: days });
}

function timeUntil(dateStr: string, t: (key: string, fallback: string, opts?: Record<string, unknown>) => string): string {
  const diff = new Date(dateStr).getTime() - Date.now();
  if (diff < 0) {
    const overdue = Math.abs(diff);
    const hrs = Math.floor(overdue / 3600000);
    if (hrs < 1) return t('tasks.time.minutesOverdue', '{{count}}m overdue', { count: Math.floor(overdue / 60000) });
    if (hrs < 24) return t('tasks.time.hoursOverdue', '{{count}}h overdue', { count: hrs });
    return t('tasks.time.daysOverdue', '{{count}}d overdue', { count: Math.floor(hrs / 24) });
  }
  const hrs = Math.floor(diff / 3600000);
  if (hrs < 1) return t('tasks.time.minutesLeft', '{{count}}m left', { count: Math.floor(diff / 60000) });
  if (hrs < 24) return t('tasks.time.hoursLeft', '{{count}}h left', { count: hrs });
  return t('tasks.time.daysLeft', '{{count}}d left', { count: Math.floor(hrs / 24) });
}

function isOverdue(task: Task): boolean {
  return !!task.slaDeadline && new Date(task.slaDeadline).getTime() < Date.now() && ['pending', 'in_progress'].includes(task.status);
}

function groupTasks(tasks: Task[]): { overdue: Task[]; today: Task[]; thisWeek: Task[]; later: Task[]; done: Task[] } {
  const endOfToday = new Date(); endOfToday.setHours(23, 59, 59, 999);
  const endOfWeek = new Date(endOfToday); endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));

  const groups = { overdue: [] as Task[], today: [] as Task[], thisWeek: [] as Task[], later: [] as Task[], done: [] as Task[] };

  for (const task of tasks) {
    if (['completed', 'dismissed', 'auto_completed'].includes(task.status)) {
      groups.done.push(task);
    } else if (isOverdue(task)) {
      groups.overdue.push(task);
    } else if (task.dueAt && new Date(task.dueAt).getTime() <= endOfToday.getTime()) {
      groups.today.push(task);
    } else if (task.dueAt && new Date(task.dueAt).getTime() <= endOfWeek.getTime()) {
      groups.thisWeek.push(task);
    } else {
      groups.later.push(task);
    }
  }

  return groups;
}

// ─── Component ───────────────────────────────────────────────

export default function Tasks() {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const [tasks, setTasks] = useState<Task[]>([]);
  const [stats, setStats] = useState<TaskStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Filters
  const [filterStatus, setFilterStatus] = useState('active');
  const [filterCategory, setFilterCategory] = useState('all');
  const [filterPriority, setFilterPriority] = useState('all');
  const [filterAssignee, setFilterAssignee] = useState('all');
  const [search, setSearch] = useState('');

  // Modals
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [selectedTasks, setSelectedTasks] = useState<Set<string>>(new Set());

  // Create form
  const [newTitle, setNewTitle] = useState('');
  const [newDescription, setNewDescription] = useState('');
  const [newPriority, setNewPriority] = useState('medium');
  const [newDueAt, setNewDueAt] = useState('');
  const [newCategory, setNewCategory] = useState('admin');
  const [creating, setCreating] = useState(false);

  const fetchTasks = useCallback(async () => {
    try {
      const params: any = { limit: '100' };
      if (filterStatus !== 'all') params.status = filterStatus;
      if (filterCategory !== 'all') params.category = filterCategory;
      if (filterPriority !== 'all') params.priority = filterPriority;
      if (filterAssignee !== 'all') params.assigneeType = filterAssignee;
      if (search.trim()) params.search = search.trim();

      const [tasksRes, statsRes] = await Promise.all([
        axios.get('/api/v1/tasks', { params }),
        axios.get('/api/v1/tasks/stats'),
      ]);

      setTasks(tasksRes.data.tasks || []);
      setStats(statsRes.data.stats || null);
      setError('');
    } catch {
      setError(t('tasks.fetchError', 'Failed to load tasks'));
    } finally {
      setLoading(false);
    }
  }, [filterStatus, filterCategory, filterPriority, filterAssignee, search, t]);

  useEffect(() => { void fetchTasks(); }, [fetchTasks]);

  const handleComplete = async (taskId: string) => {
    try {
      await axios.patch(`/api/v1/tasks/${taskId}/complete`);
      void fetchTasks();
    } catch { /* silent */ }
  };

  const handleDismiss = async (taskId: string) => {
    try {
      await axios.patch(`/api/v1/tasks/${taskId}/dismiss`, { reason: 'Dismissed by user' });
      void fetchTasks();
    } catch { /* silent */ }
  };

  const handleBulkAction = async (action: string) => {
    if (selectedTasks.size === 0) return;
    try {
      await axios.post('/api/v1/tasks/bulk-action', { taskIds: Array.from(selectedTasks), action });
      setSelectedTasks(new Set());
      void fetchTasks();
    } catch { /* silent */ }
  };

  const handleCreate = async () => {
    if (!newTitle.trim()) return;
    setCreating(true);
    try {
      await axios.post('/api/v1/tasks', {
        title: newTitle.trim(),
        description: newDescription.trim() || undefined,
        priority: newPriority,
        category: newCategory,
        dueAt: newDueAt || undefined,
      });
      setShowCreateModal(false);
      setNewTitle('');
      setNewDescription('');
      setNewPriority('medium');
      setNewDueAt('');
      setNewCategory('admin');
      void fetchTasks();
    } catch { /* silent */ }
    setCreating(false);
  };

  const handleNavigate = (url: string | null) => {
    if (url) navigate(url);
  };

  const toggleSelect = (id: string) => {
    setSelectedTasks((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const grouped = groupTasks(tasks);

  // ─── Render ──────────────────────────────────────────────

  const renderTaskCard = (task: Task) => {
    const priStyle = PRIORITY_STYLES[task.priority] || PRIORITY_STYLES.medium;
    const priLabel = t(priStyle.key, task.priority);
    const isDone = ['completed', 'dismissed', 'auto_completed'].includes(task.status);
    const overdue = isOverdue(task);

    return (
      <div
        key={task.id}
        className={`border rounded-xl p-4 transition-all ${
          overdue ? 'border-red-300 bg-red-50/50' :
          isDone ? 'border-slate-200 bg-slate-50/50 opacity-70' :
          'border-slate-200 bg-white hover:border-slate-300 hover:shadow-sm'
        }`}
      >
        <div className="flex items-start gap-3">
          {/* Checkbox */}
          {!isDone && (
            <input
              type="checkbox"
              checked={selectedTasks.has(task.id)}
              onChange={() => toggleSelect(task.id)}
              className="mt-1 h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
            />
          )}

          {/* Priority dot */}
          <div className={`mt-1.5 h-2.5 w-2.5 rounded-full shrink-0 ${priStyle.dot}`} title={priLabel} />

          {/* Content */}
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className={`text-sm font-semibold ${isDone ? 'line-through text-slate-400' : 'text-slate-900'}`}>
                {task.title}
              </h3>
              {task.assigneeType === 'agent' && (
                <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-purple-100 text-purple-700">
                  <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                  {t('tasks.badge.agent', 'Agent')}
                </span>
              )}
              {overdue && (
                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-red-100 text-red-700">
                  {t('tasks.badge.overdue', 'Overdue')}
                </span>
              )}
              {task.escalatedAt && (
                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-orange-100 text-orange-700">
                  {t('tasks.badge.escalated', 'Escalated')}
                </span>
              )}
            </div>

            {task.description && (
              <p className="mt-1 text-xs text-slate-500 line-clamp-2">{task.description}</p>
            )}

            {/* Context chips */}
            <div className="mt-2 flex items-center gap-2 flex-wrap text-xs text-slate-500">
              <span className={`px-1.5 py-0.5 rounded ${priStyle.bg} ${priStyle.color} text-[10px] font-semibold uppercase`}>
                {priLabel}
              </span>
              <span className="px-1.5 py-0.5 rounded bg-slate-100 text-slate-600 text-[10px]">
                {t(CATEGORY_KEYS[task.category] || 'tasks.category.admin', task.category)}
              </span>
              {task.job && (
                <span className="px-1.5 py-0.5 rounded bg-blue-50 text-blue-700 text-[10px] truncate max-w-[150px]">
                  {task.job.title}
                </span>
              )}
              {task.resume && (
                <span className="px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 text-[10px] truncate max-w-[120px]">
                  {task.resume.name}
                </span>
              )}
              {task.interview && (
                <span className="px-1.5 py-0.5 rounded bg-violet-50 text-violet-700 text-[10px] truncate max-w-[120px]">
                  {task.interview.candidateName}
                </span>
              )}
              <span className="text-slate-400">
                {timeAgo(task.createdAt, t)}
              </span>
              {task.slaDeadline && !isDone && (
                <span className={`font-medium ${overdue ? 'text-red-600' : 'text-slate-500'}`}>
                  {timeUntil(task.slaDeadline, t)}
                </span>
              )}
            </div>
          </div>

          {/* Actions */}
          {!isDone && (
            <div className="flex items-center gap-1 shrink-0">
              {task.actionUrl && (
                <button
                  onClick={() => handleNavigate(task.actionUrl)}
                  className="px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors"
                >
                  {task.actionLabel || t('tasks.viewAction', 'View')}
                </button>
              )}
              <button
                onClick={() => handleComplete(task.id)}
                title={t('tasks.complete', 'Complete')}
                className="p-1.5 text-slate-400 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
              </button>
              <button
                onClick={() => handleDismiss(task.id)}
                title={t('tasks.dismiss', 'Dismiss')}
                className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
              </button>
            </div>
          )}

          {isDone && (
            <div className="shrink-0">
              <span className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-medium ${STATUS_STYLES[task.status]?.color || ''}`}>
                {STATUS_STYLES[task.status] ? t(STATUS_STYLES[task.status].key, task.status) : task.status}
              </span>
            </div>
          )}
        </div>
      </div>
    );
  };

  const renderGroup = (label: string, groupTasks: Task[], icon: React.ReactNode, countColor: string) => {
    if (groupTasks.length === 0) return null;
    return (
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-3">
          {icon}
          <h2 className="text-sm font-semibold text-slate-700">{label}</h2>
          <span className={`px-1.5 py-0.5 rounded-full text-[10px] font-bold ${countColor}`}>{groupTasks.length}</span>
        </div>
        <div className="space-y-2">
          {groupTasks.map(renderTaskCard)}
        </div>
      </div>
    );
  };

  return (
    <div className="max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-slate-900">{t('tasks.title', 'Tasks')}</h1>
          <p className="text-sm text-slate-500 mt-0.5">{t('tasks.subtitle', 'Your recruitment action center')}</p>
        </div>
        <button
          onClick={() => setShowCreateModal(true)}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-medium hover:bg-blue-700 transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
          {t('tasks.createTask', 'New Task')}
        </button>
      </div>

      {/* Stats bar */}
      {stats && (
        <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-3 mb-6">
          {[
            { label: t('tasks.stats.actionRequired', 'Action Required'), value: stats.actionRequired, color: 'text-blue-700 bg-blue-50 border-blue-200' },
            { label: t('tasks.stats.overdue', 'Overdue'), value: stats.overdue, color: 'text-red-700 bg-red-50 border-red-200' },
            { label: t('tasks.stats.critical', 'Critical'), value: stats.byPriority.critical, color: 'text-red-600 bg-red-50 border-red-200' },
            { label: t('tasks.stats.high', 'High'), value: stats.byPriority.high, color: 'text-amber-600 bg-amber-50 border-amber-200' },
            { label: t('tasks.stats.completed', 'Completed'), value: stats.completed + stats.autoCompleted, color: 'text-emerald-600 bg-emerald-50 border-emerald-200' },
            { label: t('tasks.stats.total', 'Total'), value: stats.total, color: 'text-slate-600 bg-slate-50 border-slate-200' },
          ].map((s) => (
            <div key={s.label} className={`border rounded-xl px-3 py-2.5 ${s.color}`}>
              <p className="text-lg font-bold">{s.value}</p>
              <p className="text-[10px] font-medium uppercase tracking-wider opacity-75">{s.label}</p>
            </div>
          ))}
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-2 mb-5 bg-white border border-slate-200 rounded-xl p-3">
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className="text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 text-slate-700 focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
        >
          <option value="active">{t('tasks.filter.active', 'Active')}</option>
          <option value="all">{t('tasks.filter.all', 'All')}</option>
          <option value="pending">{t('tasks.filter.pending', 'Pending')}</option>
          <option value="in_progress">{t('tasks.filter.inProgress', 'In Progress')}</option>
          <option value="completed">{t('tasks.filter.completed', 'Completed')}</option>
          <option value="dismissed">{t('tasks.filter.dismissed', 'Dismissed')}</option>
        </select>
        <select
          value={filterCategory}
          onChange={(e) => setFilterCategory(e.target.value)}
          className="text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 text-slate-700 focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
        >
          <option value="all">{t('tasks.filter.allCategories', 'All Categories')}</option>
          {Object.entries(CATEGORY_KEYS).map(([k, tKey]) => <option key={k} value={k}>{t(tKey, k)}</option>)}
        </select>
        <select
          value={filterPriority}
          onChange={(e) => setFilterPriority(e.target.value)}
          className="text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 text-slate-700 focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
        >
          <option value="all">{t('tasks.filter.allPriorities', 'All Priorities')}</option>
          <option value="critical">{t('tasks.filter.critical', 'Critical')}</option>
          <option value="high">{t('tasks.filter.high', 'High')}</option>
          <option value="medium">{t('tasks.filter.medium', 'Medium')}</option>
          <option value="low">{t('tasks.filter.low', 'Low')}</option>
        </select>
        <select
          value={filterAssignee}
          onChange={(e) => setFilterAssignee(e.target.value)}
          className="text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 text-slate-700 focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
        >
          <option value="all">{t('tasks.filter.allAssignees', 'All Assignees')}</option>
          <option value="human">{t('tasks.filter.human', 'Human')}</option>
          <option value="agent">{t('tasks.filter.agent', 'Agent')}</option>
        </select>
        <div className="flex-1 min-w-[120px]">
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder={t('tasks.filter.search', 'Search tasks...')}
            className="w-full text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 text-slate-700 focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
          />
        </div>

        {/* Bulk actions */}
        {selectedTasks.size > 0 && (
          <div className="flex items-center gap-1 ml-auto">
            <span className="text-xs text-slate-500">{selectedTasks.size} {t('tasks.selected', 'selected')}</span>
            <button
              onClick={() => handleBulkAction('complete')}
              className="px-2.5 py-1 text-xs font-medium text-emerald-700 bg-emerald-50 rounded-lg hover:bg-emerald-100"
            >
              {t('tasks.bulkComplete', 'Complete')}
            </button>
            <button
              onClick={() => handleBulkAction('dismiss')}
              className="px-2.5 py-1 text-xs font-medium text-red-700 bg-red-50 rounded-lg hover:bg-red-100"
            >
              {t('tasks.bulkDismiss', 'Dismiss')}
            </button>
          </div>
        )}
      </div>

      {/* Loading */}
      {loading && (
        <div className="flex justify-center py-12">
          <div className="h-8 w-8 animate-spin rounded-full border-b-2 border-blue-600" />
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="text-center py-8 text-red-500 text-sm">{error}</div>
      )}

      {/* Empty state */}
      {!loading && !error && tasks.length === 0 && (
        <div className="text-center py-16 bg-white border border-slate-200 rounded-2xl">
          <svg className="w-12 h-12 mx-auto text-slate-300 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
          </svg>
          <h3 className="text-lg font-semibold text-slate-700 mb-1">{t('tasks.empty.title', 'All caught up!')}</h3>
          <p className="text-sm text-slate-500">{t('tasks.empty.description', 'No tasks require your attention right now.')}</p>
        </div>
      )}

      {/* Task groups */}
      {!loading && !error && tasks.length > 0 && (
        <div>
          {renderGroup(
            t('tasks.group.overdue', 'Overdue'), grouped.overdue,
            <svg className="w-4 h-4 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>,
            'text-red-700 bg-red-100',
          )}
          {renderGroup(
            t('tasks.group.today', 'Today'), grouped.today,
            <svg className="w-4 h-4 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>,
            'text-amber-700 bg-amber-100',
          )}
          {renderGroup(
            t('tasks.group.thisWeek', 'This Week'), grouped.thisWeek,
            <svg className="w-4 h-4 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>,
            'text-blue-700 bg-blue-100',
          )}
          {renderGroup(
            t('tasks.group.later', 'Later'), grouped.later,
            <svg className="w-4 h-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>,
            'text-slate-600 bg-slate-100',
          )}
          {renderGroup(
            t('tasks.group.completed', 'Completed'), grouped.done,
            <svg className="w-4 h-4 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>,
            'text-emerald-700 bg-emerald-100',
          )}
        </div>
      )}

      {/* Create Task Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="fixed inset-0 bg-black/40" onClick={() => setShowCreateModal(false)} />
          <div className="relative bg-white rounded-2xl shadow-xl w-full max-w-lg p-6 z-10">
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-lg font-bold text-slate-900">{t('tasks.createModal.title', 'Create Task')}</h2>
              <button onClick={() => setShowCreateModal(false)} className="p-1 text-slate-400 hover:text-slate-600 rounded">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">{t('tasks.createModal.taskTitle', 'Title')} *</label>
                <input
                  type="text"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
                  placeholder={t('tasks.createModal.titlePlaceholder', 'e.g., Follow up with hiring manager')}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">{t('tasks.createModal.description', 'Description')}</label>
                <textarea
                  value={newDescription}
                  onChange={(e) => setNewDescription(e.target.value)}
                  rows={3}
                  className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-100 focus:border-blue-300 resize-none"
                  placeholder={t('tasks.createModal.descriptionPlaceholder', 'Add details...')}
                />
              </div>
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">{t('tasks.createModal.priority', 'Priority')}</label>
                  <select
                    value={newPriority}
                    onChange={(e) => setNewPriority(e.target.value)}
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
                  >
                    <option value="critical">{t('tasks.priority.critical', 'Critical')}</option>
                    <option value="high">{t('tasks.priority.high', 'High')}</option>
                    <option value="medium">{t('tasks.priority.medium', 'Medium')}</option>
                    <option value="low">{t('tasks.priority.low', 'Low')}</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">{t('tasks.createModal.category', 'Category')}</label>
                  <select
                    value={newCategory}
                    onChange={(e) => setNewCategory(e.target.value)}
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
                  >
                    {Object.entries(CATEGORY_KEYS).map(([k, tKey]) => <option key={k} value={k}>{t(tKey, k)}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">{t('tasks.createModal.dueDate', 'Due Date')}</label>
                  <input
                    type="date"
                    value={newDueAt}
                    onChange={(e) => setNewDueAt(e.target.value)}
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
                  />
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-2 mt-6">
              <button
                onClick={() => setShowCreateModal(false)}
                className="px-4 py-2 text-sm font-medium text-slate-700 bg-slate-100 rounded-lg hover:bg-slate-200 transition-colors"
              >
                {t('tasks.createModal.cancel', 'Cancel')}
              </button>
              <button
                onClick={handleCreate}
                disabled={!newTitle.trim() || creating}
                className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
              >
                {creating ? t('tasks.createModal.creating', 'Creating...') : t('tasks.createModal.create', 'Create Task')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
